name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: https://github.com/AigrieTeam/frontend.git
          ref: main
          path: frontend

      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: https://github.com/AigrieTeam/backend.git
          ref: main
          path: backend
            
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag latest:$(date +%s)
