name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: username/frontend-repo
          ref: main
          path: https://github.com/AigrieTeam/frontend.git

      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: username/backend-repo
          ref: main
          path: https://github.com/AigrieTeam/backend.git
            
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag latest:$(date +%s)
