name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: AigrieTeam/frontend.git
          ref: main
          path: frontend
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: AigrieTeam/backend.git
          ref: main
          path: backend
            
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag latest:$(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image to Docker Hub
      run: |
        docker push mistergg/test-container:latest
